env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  prefer-template:
    - error
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
