env:
  commonjs: true
  node: true
  es6: true
extends: 'eslint:recommended'
rules:
  no-console:
    - off
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  prefer-template:
    - error
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
